version: 0.3
common:
  output: ""            # 导出文件位置
  field: [ ]			# 查询字段 如["website"]
cookies:
  aiqicha: ''           # 爱企查   Cookie
  tianyancha: ''        # 天眼查   Cookie
  qcc: ''               # 企查查   Cookie
  aldzs: ''             # 阿拉丁   Cookie
  xlb: ''               # 小蓝本   Token
  qimai: ''             # 七麦数据  Cookie
  chinaz: ''			# 站长之家  Cookie
  veryvp: '' 			# veryvp  Cookie
